# Generated by Django 5.2.5 on 2025-08-17 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='method',
            field=models.CharField(choices=[('Bank', 'Bank'), ('Cash', 'Cash'), ('bKash', 'bKash')], max_length=20),
        ),
    ]
