# Generated by Django 5.2.5 on 2025-08-17 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='products',
            field=models.ManyToManyField(related_name='expenses', to='core.product'),
        ),
    ]
