# Generated by Django 5.2.5 on 2025-08-19 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_expense_products_expenseproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='memo',
            field=models.FileField(blank=True, null=True, upload_to='payment_memos/'),
        ),
    ]
