# Generated by Django 5.2.5 on 2025-08-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_payment_memo'),
    ]

    operations = [
        migrations.AddField(
            model_name='return',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
