# Generated by Django 5.2.5 on 2025-08-24 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_return_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='return',
            name='amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
